"""Explicit bounded INT8 sweep space; every rejected Cartesian row is recorded."""

import itertools
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
AXES = {
    "tm": (64, 128, 256),
    "tn": (64, 128, 256),
    "tk": (64, 128, 256),
    "wm": (32, 64),
    "wn": (32, 64),
    "stages": (2, 3, 4),
}
SHARD_ROWS = 9


def legacy_rows():
    text = (ROOT / "comfy_kitchen/backends/ppu/int8_configs.inc").read_text()
    parsed = [
        tuple(map(int, re.findall(r"\d+", values)))
        for values in re.findall(r"^COMFY_PPU_INT8_CONFIG\(([^)]+)\)", text, re.M)
    ]
    if [r[0] for r in parsed] != list(range(6)) or any(len(r) != 7 for r in parsed):
        raise ValueError("legacy IDs/row arity changed; review compatibility explicitly")
    return [r[1:] for r in parsed]


def classify(row):
    tm, tn, tk, wm, wn, stages = row
    reasons = []
    if tm % wm or tn % wn:
        reasons.append("WARP_DOES_NOT_DIVIDE_TILE")
    if 32 * (tm // wm) * (tn // wn) > 1024:
        reasons.append("CTA_THREADS_GT_1024")
    if (tm + tn) * tk * stages > 262144:
        reasons.append("MAINLOOP_SMEM_GT_256KIB")
    return reasons


def census():
    accepted, rejected = [], []
    for row in itertools.product(*AXES.values()):
        reasons = classify(row)
        if reasons:
            rejected.append({"axes": dict(zip(AXES, row)), "reasons": reasons})
        else:
            accepted.append(row)
    old = legacy_rows()
    if any(row not in accepted for row in old):
        raise ValueError("sweep space lost an admitted legacy row")
    ordered = old + [r for r in accepted if r not in old]
    data = {
        "axes": AXES,
        "raw_count": len(accepted) + len(rejected),
        "accepted": [{"id": i, **dict(zip(AXES, row))} for i, row in enumerate(ordered)],
        "rejected": rejected,
        "scope": "bounded Cartesian space, not exhaustive over all possible PPU kernels",
        "resource_admission": "actual kernel static_asserts + per-device occupancy; no performance heuristic pruning",
    }
    validate_census(data)
    return data


def validate_census(data):
    expected = set(itertools.product(*AXES.values()))
    admitted = [tuple(row[key] for key in AXES) for row in data["accepted"]]
    rejected = [tuple(row["axes"][key] for key in AXES) for row in data["rejected"]]
    both = admitted + rejected
    if data["raw_count"] != len(expected) or len(both) != len(expected) or set(both) != expected:
        raise ValueError("Cartesian denominator missing, duplicated or changed")
    if [row["id"] for row in data["accepted"]] != list(range(len(admitted))):
        raise ValueError("config ID ordering changed")
    if admitted[:6] != legacy_rows():
        raise ValueError("legacy config coordinates changed")
    if any(classify(row) for row in admitted):
        raise ValueError("inadmissible row in accepted table")
    for row in data["rejected"]:
        if classify(tuple(row["axes"][key] for key in AXES)) != row["reasons"]:
            raise ValueError("rejection reason differs from the actual constraint")


def config_line(row):
    return "COMFY_PPU_INT8_CONFIG(" + ", ".join(str(row[k]) for k in ("id", *AXES)) + ")\n"


def generate(directory):
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    data = census()
    table = directory / "int8_configs_sweep.inc"
    table.write_text(
        "// Generated by tools/ppu_int8_config_space.py; do not hand edit.\n"
        + "".join(map(config_line, data["accepted"]))
    )
    (directory / "int8_config_census.json").write_text(json.dumps(data, indent=2) + "\n")
    sources, declarations, functions = [], [], []
    for start in range(0, len(data["accepted"]), SHARD_ROWS):
        index = start // SHARD_ROWS
        name = f"comfy_ppu_int8_shard_{index}"
        signature = "int dtype, int id, const ComfyPpuInt8Args* args, void* stream, int* threads, int* smem, int* occ"
        declarations.append(f'extern "C" int {name}({signature});\n')
        functions.append(name)
        cases = ""
        for row in data["accepted"][start : start + SHARD_ROWS]:
            template = ", ".join(str(row[k]) for k in AXES)
            cases += (
                f'case {row["id"]}: return comfy::ppu::run_int8_config<Output, {template}>'
                "(args, stream, threads, smem, occ);\n"
            )
        source = directory / f"int8_shard_{index:02d}.cu"
        source.write_text(
            '#include "int8_dispatch.hpp"\nnamespace {\n'
            "template<class Output> int dispatch(int id, const ComfyPpuInt8Args* args, void* stream, int* threads, int* smem, int* occ) {\n"
            "switch (id) {\n"
            + cases
            + 'default: throw std::invalid_argument("config routed to wrong shard"); } } }\n'
            f'extern "C" int {name}({signature}) {{\n switch (dtype) {{\n'
            "case 0: return dispatch<float>(id,args,stream,threads,smem,occ);\n"
            "case 1: return dispatch<cutlass::half_t>(id,args,stream,threads,smem,occ);\n"
            "case 2: return dispatch<cutlass::bfloat16_t>(id,args,stream,threads,smem,occ);\n"
            'default: throw std::invalid_argument("invalid output dtype"); } }\n'
        )
        sources.append(source)
    (directory / "int8_shard_dispatch.inc").write_text(
        f"#define COMFY_PPU_INT8_SHARD_ROWS {SHARD_ROWS}\n"
        + "".join(declarations)
        + "using ComfyInt8DispatchFn = int (*)(int,int,const ComfyPpuInt8Args*,void*,int*,int*,int*);\n"
        "static constexpr ComfyInt8DispatchFn comfy_ppu_int8_shards[] = {"
        + ",".join(functions)
        + "};\n"
    )
    return table, sources, data
